[package]
name = "mkrepo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {  workspace = true}
serde = { workspace = true}
serde_yaml = {workspace = true}
package_manager = {path = "../../package_manager", version = "*", workspace = true}